### ISSUE TITLE
Set Up Continuous Integration with GitHub Actions

### ISSUE THREAD

**Issue by Into-The-Grey** [Into-The-Grey/qRaphael#15]
# Task 3: Set Up Continuous Integration with GitHub Actions

**Description:**

Set up a CI pipeline using GitHub Actions to automate testing and deployment.

**Steps:**

1. **Create GitHub Actions Workflow Directory**
   - Create the directory for GitHub Actions workflows:
     ```bash
     mkdir -p .github/workflows
     ```

2. **Create CI Workflow File**
   - Create a workflow file named `ci.yml`:
     ```bash
     nano .github/workflows/ci.yml
     ```
   - Add the following contents:
     ```yaml
     name: CI

     on:
       push:
         branches:
           - main
       pull_request:
         branches:
           - main

     jobs:
       build:
         runs-on: ubuntu-latest

         steps:
         - uses: actions/checkout@v2

         - name: Set up Python
           uses: actions/setup-python@v2
           with:
             python-version: 3.12

         - name: Install dependencies
           run: |
             python -m venv venv
             source venv/bin/activate
             pip install torch transformers bitsandbytes tqdm

         - name: Run tests
           run: |
             source venv/bin/activate
             # Add your test command here
             pytest
     ```
