### ISSUE TITLE
Create Initial Tests for CI Pipeline

### ISSUE THREAD

**Issue by Into-The-Grey** [Into-The-Grey/qRaphael#17]
# Task 5: Create Initial Tests for CI Pipeline

**Description:**

Create initial test scripts to be run during the CI pipeline.

**Steps:**

1. **Create Test Directory**
   - Create a directory for test scripts:
     ```bash
     mkdir -p tests
     ```

2. **Create Test Script**
   - Create an initial test script named `test_sample.py`:
     ```bash
     nano tests/test_sample.py
     ```
   - Add the following contents:
     ```python
     def test_example():
         assert 1 + 1 == 2
     ```

3. **Ensure Tests Run in CI Pipeline**
   - Make sure the `pytest` command is included in the CI workflow file:
     ```yaml
     - name: Run tests
       run: |
         source venv/bin/activate
         pytest
     ```
